name: Auto-Commit Changes

on:
  push:
    branches:
      - master  # Runs on every push to the master branch

jobs:
  update-files:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN to authenticate checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        run: |
          python date_filtered_nav_dashboard.py  # Modify the script as needed

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"  # Set the Git user name
          git config user.email "actions@github.com"  # Set the Git email
          git add .  # Stage all changes
          git commit -m "Auto-update files" || echo "No changes to commit"  # Commit changes
          git push origin master  # Push the changes back to the master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to authenticate the push
