name: Auto-Commit Changes

on:
  push:
    branches:
      - master

jobs:
  update-files:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu machine

    steps:
      # Step 1: Checkout repository and use GITHUB_TOKEN for authentication
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Run Python script
      - name: Run Python Script
        run: |
          python date_filtered_nav_dashboard.py  # Run your Python script

      # Step 5: Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config user.name "anuj1963"  # Set the Git user name
          git config user.email "anujagrawal756@gmail.com"  # Set the Git user email
          git add .  # Add changes
          git commit -m "Auto-update files" || echo "No changes to commit"
          git push origin master  # Push changes back to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to authenticate the push
